### PR TITLE
restructure file tree: separate by feature first and then by file type

### PR DESCRIPTION
**Pull request by germanStabile**
Screen Shot 2019-07-22 at 7 00 00 PM

### CODE REVIEW

**Comment by mcousillas6** [comment]
Really like it! Some comments though:
- I think we should name `Views` `Models` `ViewModels` plurally to keep consistency.
- I'd drop the `Routes` folder and leave it at the root of each feature, since you should not have more than one router per feature.
- In the case of `Home`, I think it's a bit overkill to have a folder per component if you know there will not be more screens in that flow.

Also (it's probably just missing on the screenshot) what about Networking and Database services? Will there be separate folders for that?

**Comment by mato2593** [comment]
> Really like it! Some comments though:
> 
> * I think we should name `Views` `Models` `ViewModels` plurally to keep consistency.
> * I'd drop the `Routes` folder and leave it at the root of each feature, since you should not have more than one router per feature.
> * In the case of `Home`, I think it's a bit overkill to have a folder per component if you know there will not be more screens in that flow.
> 
> Also (it's probably just missing on the screenshot) what about Networking and Database services? Will there be separate folders for that?

I agree with the first two points. But I'm not completely sure about dropping the `View`, `ViewModel` folders in case there is only one from each in that component. I know it seems like too much, but at least it's consistent with every other component

**Comment by germanStabile** [comment]
Agree on the plurals. I'd still keep the Routes in its own group even though there'll only be one Route file per feature for consistency and clarity. Same thing with the Home feature, I prefer having unneeded organization than a mess 😂 
Yes, Networking layer is still organized as before in the root.

**Comment by germanStabile** [comment]
Screen Shot 2019-07-23 at 1 23 50 PM

**Pull request merged**
